services:
  mongodb:
    container_name: db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mynetwork

  nodejs:
    container_name: nodejs
    build: node_project
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork: