services:
  mongodb:
    container_name: db
    image: mongo:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - mynetwork
    ports:
      - "27017:27017"

  nodejs:
    container_name: nodejs
    build: node_project
    ports:
      - "8080:8080"
    networks:
      - mynetwork


networks:
  mynetwork: